name: riverpod_widget_annotation
description: This is a code generation annotation for widget_gen package.
version: 0.0.2
homepage: https://furkanacar.dev
repository: https://github.com/AcarFurkan/riverpod_widget_annotation
environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


flutter: